name: timeaware
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch==1.10.1
  - torchvision==0.11.2
  - torchaudio==0.10.1
  - cudatoolkit=11.3
  - scikit-learn
  - pandas
  - numpy
  - pip:
    - dgl==1.0.0+cu113 -f https://data.dgl.ai/wheels/cu113/repo.html
